browserstack in github actions

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -31,6 +31,64 @@ jobs:
     - name: Build with Gradle
       run: ./gradlew livekit-android-sdk:assembleRelease livekit-android-sdk:testRelease
 
+    - name: Import video test keys into gradle properties
+      run: |
+        sed -i -e "s,livekitApiKey=,livekitApiKey=$LIVEKIT_API_KEY,g" gradle.properties
+        sed -i -e "s,livekitApiSecret=,livekitApiSecret=$LIVEKIT_API_SECRET,g" gradle.properties
+      env:
+        LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
+        LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
+      
+    - name: Build video test app
+      run: ./gradlew video-encode-decode-test:assembleDebug video-encode-decode-test:assembleDebugAndroidTest
+      
+    - name: Video Encode Decode App upload and Set app id in environment variable.
+      run: |
+        APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@video-encode-decode-test/build/outputs/apk/debug/video-encode-decode-test-debug.apk")
+        echo "APP_UPLOAD_RESPONSE : " + $APP_UPLOAD_RESPONSE
+        APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
+        if [ $APP_ID != null ]; then
+          echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
+          echo "BROWSERSTACK_APP_ID=$APP_ID" >> $GITHUB_ENV;
+          echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
+        else
+          UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+          echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+          exit 1;
+        fi
+      env:
+        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
+        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
+
+    - name: Video Encode Decode Test Suite upload and Set test suite id in environment variable.
+      run: |
+        APP_UPLOAD_RESPONSE=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" -X POST https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite -F "file=@video-encode-decode-test/build/outputs/apk/androidTest/debug/video-encode-decode-test-debug-androidTest.apk")
+        echo "APP_UPLOAD_RESPONSE : " + $APP_UPLOAD_RESPONSE
+        APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".test_suite_url")
+        if [ $APP_ID != null ]; then
+          echo "Test Suite Apk uploaded to BrowserStack with id : ",$APP_ID;
+          echo "BROWSERSTACK_TEST_ID=$APP_ID" >> $GITHUB_ENV;
+          echo "Setting value of BROWSERSTACK_TEST_ID in environment variables to  ",$APP_ID;
+        else
+          UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
+          echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
+          exit 1;
+        fi
+      env:
+        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
+        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
+        
+    - name: Trigger BrowserStack tests
+      run: |
+        TEST_RESPONSE=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
+-X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
+-d '{"deviceLogs": true, "app": "$BROWSERSTACK_APP_ID", "testSuite": "$BROWSERSTACK_TEST_ID", "devices": ["Samsung Galaxy Tab S8-12.0","Samsung Galaxy S22-12.0", "Samsung Galaxy S21-12.0","Samsung Galaxy S20-10.0", "Google Pixel 6-12.0", "Google Pixel 5-11.0", "Google Pixel 4-11.0", "Google Pixel 3-10.0", "OnePlus 7-9.0","Xiaomi Redmi Note 8-9.0","Huawei P30-9.0"]}' \
+-H "Content-Type: application/json")
+        echo "APP_UPLOAD_RESPONSE : " + $APP_UPLOAD_RESPONSE
+      env:
+        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
+        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
+        
     - name: get version name
       if: github.event_name == 'push'
       run: echo "::set-output name=version_name::$(cat gradle.properties | grep VERSION_NAME | cut -d "=" -f2)"
